-- MySQL Script generated by MySQL Workbench
-- Fri May 26 16:23:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id_Cliente` INT NOT NULL,
  `nombre_Cliente` VARCHAR(45) NOT NULL,
  `tel_Cliente` INT NOT NULL,
  `ciudad_Cliente` VARCHAR(45) NOT NULL,
  `correo_Cliente` VARCHAR(45) NOT NULL,
  `nit_Cliente` INT NOT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `id_Rol` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `id_Empleados` INT NOT NULL,
  `nombre_empleados` VARCHAR(45) NOT NULL,
  `tel_empleados` INT NOT NULL,
  `correo_empleados` VARCHAR(45) NOT NULL,
  `id_Rol` INT NOT NULL,
  PRIMARY KEY (`id_Empleados`),
  INDEX `id_Rol_idx` (`id_Rol` ASC) VISIBLE,
  CONSTRAINT `id_Rol`
    FOREIGN KEY (`id_Rol`)
    REFERENCES `mydb`.`Rol` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartera` (
  `id_cartera` INT NOT NULL,
  `num_factura` INT NOT NULL,
  `id_Empleados` INT NOT NULL,
  `formas_pago` VARCHAR(20) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `id_Cliente` INT NOT NULL,
  PRIMARY KEY (`id_cartera`),
  INDEX `id_Cliente_idx` (`id_Cliente` ASC) VISIBLE,
  INDEX `id_Empleados_idx` (`id_Empleados` ASC) VISIBLE,
  CONSTRAINT `id_Cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `mydb`.`Cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Empleados`
    FOREIGN KEY (`id_Empleados`)
    REFERENCES `mydb`.`Empleados` (`id_Empleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `id_Empleados` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `materia_Prima` VARCHAR(45) NOT NULL,
  `recursos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Empleados`),
  CONSTRAINT `id_Empleados`
    FOREIGN KEY (`id_Empleados`)
    REFERENCES `mydb`.`Empleados` (`id_Empleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`informes_Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`informes_Laboratorio` (
  `nombre_Cliente` INT NOT NULL,
  `id_Rol` INT NOT NULL,
  `fecha_Informe` DATETIME NOT NULL,
  `estado_Prueba` VARCHAR(45) NOT NULL,
  `nombre_Informe` VARCHAR(45) NOT NULL,
  `numero_Informe` INT NOT NULL,
  PRIMARY KEY (`nombre_Cliente`),
  INDEX `id_Rol_idx` (`id_Rol` ASC) VISIBLE,
  CONSTRAINT `id_Rol`
    FOREIGN KEY (`id_Rol`)
    REFERENCES `mydb`.`Rol` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pruebas_Campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pruebas_Campo` (
  `id_TipoPrueba` INT NOT NULL,
  `direccion_Prueba` VARCHAR(45) NOT NULL,
  `fecha_Prueba` DATETIME NOT NULL,
  `id_Rol` INT NOT NULL,
  `id_Cliente` INT NOT NULL,
  `tipo_Prueba` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_TipoPrueba`),
  INDEX `id_Rol_idx` (`id_Rol` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_Cliente` ASC) VISIBLE,
  CONSTRAINT `id_Rol`
    FOREIGN KEY (`id_Rol`)
    REFERENCES `mydb`.`Rol` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `mydb`.`Cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Prueba` (
  `id_TipoPrueba` INT NOT NULL,
  `sondeos` VARCHAR(45) NOT NULL,
  `inspecciones_Ultra` VARCHAR(45) NOT NULL,
  `esclorometrias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_TipoPrueba`),
  CONSTRAINT `id_TipoPrueba`
    FOREIGN KEY (`id_TipoPrueba`)
    REFERENCES `mydb`.`pruebas_Campo` (`id_TipoPrueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
